config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register"}
  
  get "about" => "pages#about", as: "about"
  get "contact" => "pages#contact", as: "contact"
  get "home" => "pages#home", as: "home"

  resources :blogs
  get ":id/change_status" => "blogs#toggle_status", as: "toggle_status"

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get "angular-items" => "portfolios#angular", as: "angular_items"
  get "portfolio/:id" => "portfolios#show", as: "show_portfolio"

  root "pages#home"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	enum status: { draft: 0, published: 1 }
	extend FriendlyId
	friendly_id :title, use: :slugged
	validates_presence_of :title, :body
	belongs_to :topic


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @topics = Topic.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'The blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  def toggle_status
    @blog = Blog.friendly.find(params[:id])
    if @blog.published?
      @blog.draft!
    else
      @blog.published!
    end
    redirect_to blogs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper

	def show_normal_date(date)
		date.strftime("%d %b. %Y")
	end
	
end

app/views/blogs/_blog-form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Publish", class: "button primary" %>
  </div>
<% end %>

app/views/blogs/_blog.html.erb
<%= link_to blog_path blog do %>	

	<div class="blog-post">

		<h2 class="blog-post-title"><%= blog.title %></h2>

		<p><%= blog.published? ? "Udgivet" : "Kladde" if logged_in?(:site_admin) %></p>
		<p class="btn"><%= link_to('Ændre status', toggle_status_path(blog)) if logged_in?(:site_admin) %></p>
		<p class="btn"><%= link_to('Show', blog) if logged_in?(:site_admin) %></p>
		<p class="btn"><%= link_to('Edit', edit_blog_path(blog)) if logged_in?(:site_admin) %></p>
		<p class="btn"><%= link_to('Delete post', blog, method: :delete, data: { confirm: 'Are you sure?' }) if logged_in?(:site_admin) %></p>
		<p class="blog-post-meta">Udgivet: 
		<%= distance_of_time_in_words(blog.created_at, Time.now) %></p>
		<p><%= blog.body %></p>


	</div><!-- /.blog-post -->
	
<% end %> <!-- bog_path -->

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Publish", class: "button primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="row">

    <div class="col-sm-8 blog-main">
	<%= paginate @blogs %>

    <%= render @blogs %>

    </div>
    <%= render partial: "shared/blogsidebar", locals: {topics: @topics} %>

  </div>
  <%= paginate @blogs %>
</div>


<%= link_to 'New Blog', new_blog_path, class: "button primary" if logged_in?(:site_admin) %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'blog-form' %>

<%= link_to 'Back', blogs_path, class: "button alert" %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<p><strong>Created:</strong>
<%=	show_normal_date(@blog.created_at) %>
</p>

<p><strong>Last updated:</strong>
<%=	show_normal_date(@blog.updated_at) %>	
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>