config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register"}
  
  get "about" => "pages#about", as: "about"
  get "contact" => "pages#contact", as: "contact"
  get "home" => "pages#home", as: "home"

  resources :blogs
  get ":id/change_status" => "blogs#toggle_status", as: "toggle_status"

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get "angular-items" => "portfolios#angular", as: "angular_items"
  get "portfolio/:id" => "portfolios#show", as: "show_portfolio"

  root "pages#home"

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	include Placeholder
	mount_uploader :main_image, PortfolioUploader
	
	has_many :technologies
	accepts_nested_attributes_for :technologies,
									reject_if: lambda { |attr| attr["name"].blank? }

	validates_presence_of :title, :body, :main_image, :thumb_image

	def self.angular 
		where(subtitle: "Angular")
	end

	def self.by_position
		order(position: :asc)
	end

	# A portfolio items is initilized when Portfolio.new is called. 
	after_initialize :set_default

	def set_default
	# Hvis det ikke var ||=, men =, så ville det blive overskrevet, når det var 	
	self.main_image ||= Placeholder.image_generator(height: 400, width: 600)
	self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)

	end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolio, only: [:edit, :show, :update, :destroy]
	layout "portfolio"
	access all: [:show, :index, :angular], user: {except: [:sort, :destroy, :new, :create, :update, :edit]}, site_admin: :all

	def index
		@portfolio_items = Portfolio.by_position
	end	

	def sort
		params[:order].each do |key, value|
			Portfolio.find(value[:id]).update(position: value[:position])
		end

		render nothing: true
	end

	def angular
		@angular_portfolio_items = Portfolio.angular
	end

	def show
		@portfolio_item = Portfolio.find(params[:id])
	end

	def new
		@portfolio_item = Portfolio.new
		3.times { @portfolio_item.technologies.build }
	end



	def create 
		@portfolio_item = Portfolio.new(portfolio_params)

		respond_to do |format| 
			if @portfolio_item.save
				format.html { redirect_to portfolios_path , notice: "Your portfolio item was saved."}
			else
				format.html { render :new }			
			end
		end

	end

	def edit
		@portfolio_item = Portfolio.find(params[:id])		
		3.times { @portfolio_item.technologies.build }

	end

	def update
		respond_to do |format|
			if @portfolio_item.update_attributes(portfolio_params)
				format.html { redirect_to portfolios_path, notice: "Item was succesfully created."}
			else
				format.html { render :edit }
			end 
		end
	end


	def destroy
		@portfolio_item.destroy
		respond_to do |format|
			format.html { redirect_to portfolios_path, notice: "Portfolio_item was removed."}

		end	
	end
	private 

	def portfolio_params
		params.require(:portfolio).permit(:title, 
			:subtitle, 
			:body, 
			:main_image,
			{technologies_attributes: [:name]}
			)
	end

	def set_portfolio
		@portfolio_item = Portfolio.find(params[:id])
	end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :subtitle %>
<%= f.text_field :subtitle %>

<%= f.label :body %>
<%= f.text_area :body %>

<%= f.label :main_image, "Tilføj billede" %>
<%= f.file_field :main_image %>

<ul>
	<%= f.fields_for :technologies do |tec_form| %> 
		<li>
		<%= tec_form.label :name %>
		<%= tec_form.text_field :name %>
		</li>
	<% end %>
</ul>


<%= f.submit "Tilføj", class: "button" %>
<% end %>

app/views/portfolios/_portfolio-form.html.erb
<%= form_for(portfolio_item) do |f| %>
<div class="row portfolio-container">
	<div class="col-md-6">
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :subtitle %>
			<%= f.text_field :subtitle, class: "form-control" %>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, rows: 10, class: "form-control" %>
		</div>
	</div>
</div><!-- row -->
<div class="row">
<div class="col-md-12">
	<div class="form-group">
		<%= f.label :main_image, "Tilføj billede" %>
		<%= f.file_field :main_image, class: "form-control" %>
	</div>

	<%= f.fields_for :technologies do |tec_form| %> 
	<div class="form-group">
		<%= tec_form.label :name %>
		<%= tec_form.text_field :name, class: "form-control" %>
	</div>
	<% end %>
</div>
</div>
<div class="form-group">
	<%= f.submit "Tilføj", class: "btn btn-primary btn-block" %>
	<% end %>
</div>

app/views/portfolios/_portfolio.html.erb
<div class="card" data-id="<%= portfolio.id %>">
<%= link_to show_portfolio_path(portfolio) do %> 
	<strong><h4><%= portfolio.title %></h4></strong>
	<%= image_tag portfolio.main_image.thumb.url, alt: "Card image cap"%>
  <p class="card-text"><%= portfolio.subtitle %></p>
<% end %>
</div>

app/views/portfolios/angular.html.erb
<h1>Portfolio items</h1>
<%= link_to "Opret nyt item", new_portfolio_path, class: "button warning" %>
<% @angular_portfolio_items.each_with_index do |item, num| %>
		<%= link_to show_portfolio_path(item), method: :get do %>
			<p><strong><%= item.title %></strong></p>
			<p><%= item.subtitle %></p>
			<%= image_tag item.thumb_image unless item.thumb_image.nil? %>
			<%= link_to "Rediger", edit_portfolio_path(item) %>
			<%= link_to "Slet", portfolio_path(item), method: :delete, data: { confirm: "Er du sikker?" } %>
		<% end %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-item">
<h1>Create a new portfolio item.</h1>


<%= render partial: "portfolio-form", locals: {:portfolio_item => @portfolio_item } %>

<%= link_to "Gå tilbage", portfolios_path, class: "button secondary" %>

</div>

app/views/portfolios/index.html.erb
 
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
    <%= render @portfolio_items %>
    </div>

<%= link_to("Opret nyt item", new_portfolio_path, class: "button warning") if logged_in?(:site_admin) %>

app/views/portfolios/new.html.erb
<div class="container portfolio-item">
<h1>Create a new portfolio item.</h1>

<%= render partial: "portfolio-form", locals: { portfolio_item: @portfolio_item } %>

<%= link_to "Gå tilbage", portfolios_path, class: "button secondary" %>

</div>

app/views/portfolios/show.html.erb
<div class="row portfolio-container">
	<div class="col-md-5">

		<%= image_tag @portfolio_item.main_image, width: "100%", id: "mainImage"%>

	</div>
	<div class="col-md-7 text-left">

		<h2><%= @portfolio_item.title %></h2>

		<p><%= @portfolio_item.body %></p>

		<h2>Used Tech</h2>

		<% @portfolio_item.technologies.each do |item| %>
		<p><%= item.name %></p>
		<% end %>

		<%= link_to "Rediger", edit_portfolio_path(@portfolio_item), class: "btn btn-primary" if logged_in?(:site_admin) %>


	</div>


</div>
<hr>
<div class="row">
	<div class="col-md-6">
		<%= link_to "Gå tilbage til oversigt", portfolios_path, class: "btn btn-secondary" %>
	</div>
	<div class="col-md-6">
	<%= link_to "Gå til top", "#", class: "btn btn-secondary float-right" %>
	</div>
</div>


</div>